//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.41222.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace RSSReader.Properties {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSSReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap channel_delete {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("channel_delete", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap channel_edit {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("channel_edit", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap channel_new {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("channel_new", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap folder_add {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("folder_add", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap folder_delete {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("folder_delete", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap folder_edit {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("folder_edit", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap folder_new {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("folder_new", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap rss {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("rss", resourceCulture)));
            }
        }
    }
}
